# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: '一站式micro:bit学习平台'
site_description: 'ElecFreaks Product Document'
site_author: 'Will'
site_url: 'https://www.elecfreaks.com/learn-cn/'

# Repository
repo_name: 'Microbit'
repo_url: 'https://github.com/elecfreaks/learn-cn'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 ElecFreaks'

# Theme directory
theme_dir: material

# Icon
#site_favicon: 'docs/images/favicon.ico'
site_favicon: https://raw.githubusercontent.com/elecfreaks/learn-cn/master/docs/images/favicon.ico

# Configuration
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: light green
    accent: 'indigo'    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/favicon.ico'
  search:
    language: 'cn'
    tokenizer: '[\s\-\.]+'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/elecfreaks/learn-cn'
    - type: 'facebook'
      link: 'https://www.facebook.com/ElecFreaksTech/'
    #- type: 'linkedin'
    #  link: 'https://linkedin.com/in/squidfunk'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.keys

# Page tree
pages:
  - 欢迎来到micro:bit知识库: 'index.md'

  - microbit 基础教程:
    - BBC micro:bit: Micro_bit_Board.md
    - 课堂趣味项目: 
        - 闪烁的心: 闪烁的心.md
        - 笑脸: 笑脸.md
        - 爱心表: 爱心表.md
        - 剪刀石头布: 剪刀石头布.md
        - 按钮魔术: 按钮魔术.md
        - 抛硬币: 抛硬币.md
        - Salute数学游戏: Salute数学游戏.md
        - 改造你的耳机: 改造你的耳机.md
        - 香蕉键盘: 香蕉键盘.md
        - 吉他: 吉他.md
        - 钱包: 钱包.md
        - 手表: 手表.md
        - 倒计时器: 倒计时器.md
        - 电子手表: 电子手表.md
        - 土壤湿度: 土壤湿度.md
        - 自动浇花: 自动浇花.md
        - 反应时间: 反应时间.md
        - 物质状态: 物质状态.md
        - 情绪无线电: 情绪无线电.md
        - 土豆电报: 土豆电报.md
        - 冷或热: 冷或热.md
        - 投票机: 投票机.md
        - 感染: 感染.md
        - 萤火虫: 萤火虫.md
        - 剪刀石头布小组: 剪刀石头布小组.md
        - 微币: 微币.md
        - 毛毛虫: 毛毛虫.md
        - 牛奶怪兽: 牛奶怪兽.md
        - RC小车: RC小车.md
        - 计时门槛: 计时门槛.md
        - 指南针: 指南针.md
        - 电报: 电报.md
        - 铁路交通灯: 铁路交通灯.md
        - Karel艺术: Karel艺术.md
        
    - micro:bit技术博客:
        - 如何使用蓝牙: 如何使用蓝牙（IOS系统）.md
    
  - Micropython 系列教程:
    - 1 准备开始Micropython学习: 
          - 1.1 什么是micro:bit: micropython1_1.md
          - 1.2 什么是Python: micropython1_2.md
          - 1.3 工具及环境: micropython1_3.md
          - 1.4 小结: micropython1_4.md
    - 2 第一个MicroPython案例: 
          - 2.1 Hello world: micropython2_1.md
          - 2.2 Python中的程序结构: micropython2_2.md
          - 2.3 Python中的基础语法: micropython2_3.md
          - 2.4 什么是API: micropython2_4.md
    - 3 LED点阵显示屏: 
          - 3.1 Python中的数据类型和变量: micropython3_1.md
          - 3.2 Python中的运算符: micropython3_2.md
          - 3.3 显示屏的相关API: micropython3_3.md
          - 3.4 演示案例: micropython3_4.md
          - 3.5 课后练习: micropython3_5.md
    - 4 A+B独立按键: 
          - 4.1 Python中的循环语句: micropython4_1.md
          - 4.2 Python中的条件语句: micropython4_2.md
          - 4.3 按键相关API: micropython4_3.md
          - 4.4 演示案例: micropython4_4.md
          - 4.5 课后练习: micropython4_5.md
    - 5 输入输出IO口: 
          - 5.1 什么是输入输出引脚: micropython5_1.md
          - 5.2 PWM及相关API: micropython5_2.md
          - 5.3 演示案例: micropython5_3.md
          - 5.4 课后练习: micropython5_4.md
    - 6 音乐: 
          - 6.1 蜂鸣器: micropython6_1.md
          - 6.2 播放内置音乐: micropython6_2.md
          - 6.3 播放自定义音调: micropython6_3.md
          - 6.4 演示案例: micropython6_4.md
          - 6.5 课后练习: micropython6_5.md
    - 7 加速度计与罗盘: 
          - 7.1 Python中的随机数:  micropython7_1.md
          - 7.2 加速度计: micropython7_2.md
          - 7.3 指南针: micropython7_3.md
          - 7.4 演示案例: micropython7_4.md
          - 7.5 课后练习: micropython7_5.md
    - 8 函数: 
          - 8.1 Python中的函数: micropython8_1.md
          - 8.2 变量作用域: micropython8_2.md
          - 8.3 演示案例: micropython8_3.md
          - 8.4 课后练习: micropython8_4.md
    - 9 无线电电与蓝牙: 
          - 9.1 Bluetooth蓝牙: micropython9_1.md
          - 9.2 无线电相关API: micropython9_2.md
          - 9.3 演示案例: micropython9_3.md
          - 9.4 课后练习: micropython9_4.md
          
 
  - micro:bit 套件: 
    - micro:bit 小小科学家套件:
        - Micro:bit 小小科学家套件: Micro_bit_Starter_Kit.md
        - 面包板扩展板（breadboard:bit）: Micro_bit_Breadboard_Adapter_CN.md
        - 小小科学家套件课程_01 LED: Micro_bit_Starter_Kit_Lesson_01_LED_CN.md
        - 小小科学家套件课程_02 按钮: Micro_bit_Starter_Kit_Lesson_02_Button_CN.md
        - 小小科学家套件课程_03 电位器: Micro_bit_Starter_Kit_Lesson_03_Trimpot_CN.md
        - 小小科学家套件课程_04 光敏电阻: Micro_bit_Starter_Kit_Lesson_04_Photocell_CN.md
        - 小小科学家套件课程_05 三色LED: Micro_bit_Starter_Kit_Lesson_05_RGB_LED_CN.md
        - 小小科学家套件课程_06 自锁开关: Micro_bit_Starter_Kit_Lesson_06_Self_lock_Switch_CN.md
        - 小小科学家套件课程_07 温度传感器: Micro_bit_Starter_Kit_Lesson_07_Temperature_Sensor_CN.md
        - 小小科学家套件课程_08 舵机: Micro_bit_Starter_Kit_Lesson_08_Servo_CN.md
        - 小小科学家套件课程_09 蜂鸣器: Micro_bit_Starter_Kit_Lesson_09_Buzzer_CN.md
        - 小小科学家套件课程_10 电机: Micro_bit_Starter_Kit_Lesson_10_Motor_CN.md
        - 小小科学家套件课程_11 七彩灯环: Micro_bit_Starter_Kit_Lesson_11_Rainbow_LED_CN.md
        - 小小科学家套件课程_12 加速度计: Micro_bit_Starter_Kit_Lesson_12_Accelerometer_CN.md
        - 小小科学家套件课程_13 指南针: Micro_bit_Starter_Kit_Lesson_13_Compass_CN.md
        - 小小科学家套件课程_14 环境光: Micro_bit_Starter_Kit_Lesson_14_Ambient_Light_CN.md
          
    - micro:bit 小小发明家套件: 
        - micro:bit 小小发明家套件: Micro_bit_Tinker_Kit.md
        - 5V传感器扩展板（octopus:bit）: Octopus_bit_CN.md
        - 小小发明家套件课程_01 音乐播放器: Micro_bit_Tinker_Kit_Case_01_Music_Machine_CN.md
        - 小小发明家套件课程_02 智能灯: Micro_bit_Tinker_Kit_Case_02_Smart_Light_CN.md
        - 小小发明家套件课程_03 电子琴: Micro_bit_Tinker_Kit_Case_03_Electro_Theremin_CN.md
        - 小小发明家套件课程_04 报警装置: Micro_bit_Tinker_Kit_Case_04_Simple_Alarm_Box_CN.md
        - 小小发明家套件课程_05 土壤湿度检测: Micro_bit_Tinker_Kit_Case_05_Plant_Monitoring_Device_CN.md
        - 小小发明家套件课程_06 入侵检测: Micro_bit_Tinker_Kit_Case_06_Intruder_Detection_CN.md
        - 小小发明家套件课程_07 喂鱼器: Micro_bit_Tinker_Kit_Case_07_Fish_Feeder_CN.md
        - 小小发明家套件课程_08 运动检测: Micro_bit_Tinker_Kit_Case_08_Motion_Detector_CN.md
        - 小小发明家套件课程_09 测谎仪: Micro_bit_Tinker_Kit_Case_09_Lie_Detector_CN.md
        - 小小发明家套件课程_10 乒乓球游戏: Micro_bit_Tinker_Kit_Case_10_PADDLEBALLSUPERSMASHEM_CN.md
        - 小小发明家套件课程_11 躲避小行星: Micro_bit_Tinker_Kit_Case_11_Avoid_Asteroids_CN.md
        - 小小发明家套件课程_12 遥控小车: Micro_bit_Tinker_Kit_Case_12_Remote_Control_Everything_CN.md
        - 小小发明家套件课程_13 micro:bit小车: Micro_bit_Tinker_Kit_Case_13_Micro_Bit_Car_CN.md
        - 小小发明家套件课程_14 抛煎饼游戏: Micro_bit_Tinker_Kit_Case_14_Flipping_Pancakes_CN.md
        - 小小发明家套件课程_15 跑迷宫游戏: Micro_bit_Tinker_Kit_Case_15_Maze_Runner_CN.md
        - 小小发明家套件课程_16 速算游戏: Micro_bit_Tinker_Kit_Case_16_QUICK_MATHS_CN.md
        - 小小发明家套件课程_17 猜音调游戏: Micro_bit_Tinker_Kit_Case_17_Pitch_Perfect_CN.md
        - 小小发明家套件课程_18 手指灵敏度游戏: Micro_bit_Tinker_Kit_Case_18_Finger_Dexterity_CN.md
        - 小小发明家套件课程_19 电子水平仪: Micro_bit_Tinker_Kit_Case_19_Electric_Spirit_Level_CN.md
        - 小小发明家套件课程_20 太空射击游戏: Micro_bit_Tinker_Kit_Case_20_Space_Shooter_CN.md
        - 小小发明家套件课程_21 飞行的小鸟游戏: Micro_bit_Tinker_Kit_Case_21_Flappy_Bird_CN.md
        - 小小发明家套件课程_22 摩尔斯代码信息传输: Micro_bit_Tinker_Kit_Case_22_Wire_Transmission_CN.md
        - 小小发明家套件课程_23 贪吃蛇游戏: Micro_bit_Tinker_Kit_Case_23_Snake_Game_CN.md
                   
    - micro:bit 手表套件:
        - 钮扣电池扩展板（power:bit）: power_bit.md
        - 手表套件介绍: watch_kit.md
        - 案例01：便携指南针: watch_kit_case_01.md
        - 案例02：骰子: watch_kit_case_02.md
        - 案例03：便携温度计: watch_kit_case_03.md
        - 案例04：定时器: watch_kit_case_04.md
        - 案例05：多功能手电筒: watch_kit_case_05.md
          
    - micro:bit 基础套件: 
        - 基础套件简介: basic_kit.md
        - 3路IO基础扩展板（basic:bit）: Basic_bit_CN.md
        - 案例01：灯光控制器: basic_kit_case_01.md
        - 案例02：摩斯密码: basic_kit_case_02.md
        - 案例03：功能选择器: basic_kit_case_03.md	
		
    - Ring:bit 小车套件: 
        - Ring:bit 小车套件: Ring_bit_Car_Kit_CN.md
        - 3路IO带电池盒扩展板（Ring:bit）: Ring_bit_CN.md
        - 案例01 添加代码库: Ring_bit_Car_Kit_Case_01_Add_Package_CN.md
        - 案例02 折线行走: Ring_bit_Car_Kit_Case_02_S_Walk_CN.md
        - 案例03 画圆: Ring_bit_Car_Kit_Case_03_Draw_a_Circel_CN.md
        - 案例04 无线遥控: Ring_bit_Car_Kit_Case_04_Wireless_Remote_Control_CN.md
          
    - motor:bit 智能小车套件: 
        - 两路电机驱动板（motor:bit）: Motor_bit_V16.md
        - motor:bit 智能小车简介: motor_bit_smart_car.md
        - 案例01 定点停车: motor_bit_smart_car_case_01.md
        - 案例02 保持距离: motor_bit_smart_car_case_02.md
        - 案例03 巡线绕圈: motor_bit_smart_car_case_03.md
        - 案例04 自动避障: motor_bit_smart_car_case_04.md
        - 案例05 遥控小车: motor_bit_smart_car_case_05.md
        - 案例06 蓝牙控制: motor_bit_smart_car_case_06.md
          
  - micro:bit 独立扩展板及模组:
    - 3V传感器扩展板（sensor:bit）: Sensor_bit.md
    - 金手指扩展板(edge:bit): edge_bit_CN.md
    - micro:bit 电源模块: Micro_bit_Power_Supply_Module_3.3V_2A_CN.md
    - mBot扩展版（robit）: 
        - mBot扩展版介绍: Robit_CN.md
        - 案例01 超声波测距: Robit_Case_01.md
        - 案例02 超声波避障: Robit_Case_02.md
        - 案例03 永不坠落的小车: Robit_Case_03.md
        - 案例04 巡线: Robit_Case_04.md
        - 案例05 倒车报警: Robit_Case_05.md
        - 案例06 彩虹LED: Robit_Case_06.md
        - 案例07 自动车灯: Robit_Case_07.md
        - 案例08 手机遥控: Robit_Case_08.md 
        
        
  - micro:bit 电子积木传感器:
    - 蓝色电位器电子积木: octopus_ef04085.md
    - 3V 继电器电子积木: octopus_ef04086.md
    - BME280 气压电子积木: octopus_ef04087.md
    - 3线宽压超声波电子积木: sonar_bit.md
    - 两路巡线模块电子积木: octopus_ef04088.md  
	
  - micro:bit 其他配件:
    - 2xAA 无盖电池盒: 2xAA_Battery_Holder_without_Cover.md
    - 2xAA 有盖带开关电池盒: 2xAA_Battery_Holder_With_ON_OFF_Switch_and_Cover.md
    - micro:bit外壳: Micro_case_CN.md
    - micro:bit外壳带AA电池盒: Acrylic_Case_with_Two_AA_Battery_Holder.md
    - Motor:bit小车底盘: Smart_Car_Chassis_for_motor_bit_CN.md 
	
	
	
# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'
